### ISSUE TITLE
[SUCCESS]Questions about caps lock...

### ISSUE THREAD

**Issue by AllCheeks** [wangwei39120157028/BadUSB#2]
Hello, excuse me
How can I keep him in lowercase
uppercase commands cannot be run

example:
Keyboard.print("hello");
But the output Notepad becomes
HELLO
----------------------------------------------
或许我该使用中文
请问和键盘的大小写CapsLock冲突怎么办
大写的命令有些无法运行

**Comment by wangwei39120157028** [comment]
如果你使用的是Windows系统的话，命令行cmd有一些可以强制调整字母大小写的快捷键，不妨试一下。
If you are using a Windows system, the command line cmd has some shortcut keys that can force the case adjustment of letters. Try it.
